server:
  port: 8090
  servlet:
    context-path: /app

spring:
  mvc:
    static-path-pattern: /statico/**
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/market?serverTimezone=UTC
    username: root
    password: Nbirf
management:
  endpoints:
    web:
      exposure:
        include: info, health, beans, mappings








